- name: Gather structured facts for network resources
  hosts: ios
  gather_facts: false
  tasks:
    - name: Invoke gather role
      ansible.builtin.include_role:
        name: network.inventory_reports.gather
      vars:
        format: json
        resources:
          - "bgp_global"
          - "bgp_address_family"
          - "interfaces"
         
 
        




    
