---
- name: generate WEB report
  hosts: ansible_1
  become: true
  tasks:
    - name: Generate report
      ansible.builtin.include_role:
        name: network.inventory_reports.generate_report
      vars:
        resources:
          - "interfaces"
          - "l3_interfaces"
        data_store:
            scm:
              parent_directory: "/data/ansible-scm"  # ✅ Add this line!
              origin:
                url: "https://github.com/AAYUSH2091/testing_1.git"
                token: "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"
                user:
                  name: "AAYUSH2091"
                  email: "aaanand@redhat.com"

        
